### ISSUE TITLE
Today button not working

### ISSUE THREAD

**Issue by alexfrad** [t1m0n/air-datepicker#179]
Hi, i''ve been using this for not a long time and recently i got feedback that the today button was not working. I went through the code to see that it never get through the if statement in the today function because this.opts.todayButton is a true/false and not a Date.
`today: function () {
            this.silent = true;
            this.view = this.opts.minView;
            this.silent = false;
            this.date = new Date();

            if (this.opts.todayButton instanceof Date) {  //Never pass this
                this.selectDate(this.opts.todayButton)
            }
        },`
Here's how i initialise it: 
`$("#clock_on_date").datepicker( {
           language: i18next.t("language_shortcut"),
           dateFormat: "yyyy/mm/dd",
           todayButton: 'true',
           autoClose: 'true'
       });`

Thanks for you help.

**Comment by t1m0n** [comment]
Hello! If `true` is passed for `todayButton`, there will be only a transition to current date without selecting one. If you want to also select this date, when you'll have to pass `new Date()` (or any other desirable date) instead of boolean. 
Here is example of selecting current date - https://jsfiddle.net/wqy56k8h/

**Comment by alexfrad** [comment]
It's working thank you! Strange thing is that it was working the first time I added the plugin
