### ISSUE TITLE
Using locale file without npm/webpack

### ISSUE THREAD

**Issue by xtianus** [t1m0n/air-datepicker#440]
I'm loading the dist javascript with a plain <script> tag from my HTML but if I also load the locale file I get the error

```
Uncaught ReferenceError: exports is not defined
   at fr.js:3
```

**Comment by User12987** [comment]
As I understood, decision could be in use your own locale settings. For example:

```html
<div id="dp"></div>
```

```javascript

// ...including AirDatePicker and it's CSS

// locale setup
const localeEs = {
    days: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    daysShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', ],
    daysMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
    months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Dic'],
    today: 'Hoy',
    clear: 'Cancelar',
    dateFormat: 'dd/mm/yyyy',
    timeFormat: 'hh:ii',
    firstDay: 1
}

// creating date picker with locale
new AirDatepicker('#dp', {
    locale: localeEs
})
```
![Снимок экрана 2021-10-07 в 12 15 48](https://user-images.githubusercontent.com/44153099/136324524-8227a70f-49eb-4978-85ac-7a0f6a5b542f.png)


I'm not sure that it is working code for you, cause I check it over webpack 5 build.

**Comment by t1m0n** [comment]
Unfortunately localization files works only through `import`. @User12987  is right, if you dont have opportunity to use `import` in your project, then you could declare localization straight in datepicker initialization.

**Comment by MagnusOxlund** [comment]
If ES6 `export` declarations were used in the distributed locale files, plain static ES6 `import` declarations would be able to access them.

Any chance such a change could be made?

**Comment by racilhilan** [comment]
If you want to load the dist files with `<script>` tags, you can use a workaround based on the following notes:

- The locale settings will try to attach themselves to an object called "exports" which doesn't exists because you're loading the files with `<script>` tags, and that's why you get the error _"exports is not defined"_. So you'll have to provide that object (can be empty) before you load the locale script.
- The main object "AirDatepicker" keeps a default locale in its "defaults" property, so you can access it using `AirDatepicker.defaults.locale`. It uses this value to populate the locale when you call it to enhance the element. You can set it to the value that was saved into the "exports.default" object or the intermediary "_default" object, then you can clear both objects to keep the code clean.

Here is an example with the workaround:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/air-datepicker@3.6.0/air-datepicker.css">
</head>
<body>

<input id="calendar" type="text" />

<script src="https://cdn.jsdelivr.net/npm/air-datepicker@3.6.0/air-datepicker.js"></script>
<script type="text/javascript">
    var exports = {};
</script>
<script src="https://cdn.jsdelivr.net/npm/air-datepicker@3.6.0/locale/en.js"></script>
<script type="text/javascript">
    AirDatepicker.defaults.locale = _default;
    _default = undefined;
    exports = undefined;
</script>
<script type="text/javascript">
    new AirDatepicker('#calendar');
</script>
</body>
</html>
```
