### ISSUE TITLE
Range of dates: problem when first day is equal to last day

### ISSUE THREAD

**Issue by gitantonio** [t1m0n/air-datepicker#85]
Hi,
it is possible to select (also) same day in modality `{range: true}`?

Now, when I select first day (and I *don't* select last day), the highlight selection remains to the end of week.
Do you intend fix this?

Regards,
Antonio

**Comment by t1m0n** [comment]
Hi, yes you can select same day if `range:true`, since `v2.1.0`. 
As for selection, it is not a bug or something, it's just how it works - calendar highlights all dates after or before selected cell till another selected or focused cell. When you leave calendar, last focused date is being saved, and selection remains visible, not sure if this behavior should be changed.

**Comment by gitantonio** [comment]
Ok, thanks!

I will use it in a project with `{inline: true}`. I that modality, unfortunately, the highlight selection could be a problem, because it could mislead the user.
