### ISSUE TITLE
onRenderCells returns the false Date

### ISSUE THREAD

**Issue by eSport-Designs** [t1m0n/air-datepicker#97]
Hi,

when I disable a day, the following date gets disabled. Here is my code:
`onRenderCell: function(date, cellType) {
		
			if(date.toISOString().slice(0,10) == "2016-08-03") {
				return {
					disabled: true,
				}
			}
		}`

I try to disable the 2016-08-03, but the following 2016-08-04 gets disabled. 

best regards

**Comment by t1m0n** [comment]
Hello, it happens because of date which is passed is in local format, and does include time zone shift. When it converted to UTC format, `toISOString` subtracts or adds this shift to make it equal to **0**. So, for example, if date is `2016-08-04 00:00:00 GMT+0300` it has time zone shift equal to 3 hours, when it converted to UTC format, `toISOString` subtracts from date 3 hours and we get new date which is equal to `2016-08-03 21:00:00`, and that is why 4 is disabled instead of 3.

Another words, you should convert passed date to UTC format, and after that use `toISOString()`:
```javascript
onRenderCell: function (date, type) {
    // Get time zone offset in ms
    var offset = date.getTimezoneOffset()*60000; 
    // Create new date
    date = new Date(d.getTime() - offset); 

    if(date.toISOString().slice(0,10) == "2016-08-03") {
        return {
            disabled: true
        }
    }
}

```
